spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notificationdb?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Snmysql@1110}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  <!-- flyway: 
      enabled: true
      locations: classpath:db/migration -->

notify:
  encryption:
    key: ${NOTIFY_ENC_KEY:ChangeThisTo32ByteKey_ReplaceInProd!}
  hmac:
    key: ${NOTIFY_HMAC_KEY:ChangeThisToAnotherKeyForHMAC_ReplaceInProd!}

security:
  access-token: ${ACCESS_TOKEN:change_this_token}

server:
  port: 8082
  
jwt:
  public-key-path: classpath:keys/jwt-public.pem



auth:
  service:
    url: http://localhost:8081/api/
  client-id: notification-service
  client-secret: notify-secret

